"""empty message

Revision ID: fcc2182df600
Revises: 
Create Date: 2021-03-10 20:42:12.634555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcc2182df600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=280), nullable=True),
    sa.Column('big_text', sa.String(), nullable=True),
    sa.Column('text_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_texts')
    # ### end Alembic commands ###
